feat: frontend for creating recurring payments
faktorfi/faktor pull request #7
Opened 2021-11-15 18:07 UTC by rasreee

2021-11-18 23:56 UTC, nickgarfield requested changes
Looks good! Just a few questions and requests here and there. Open to chatting about any of them if you want to hop on a huddle!

2021-11-18 23:56 UTC, nickgarfield commented on .gitignore
> +test-ledger
👍

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/CreatePaymentModal/CreatePaymentModal.tsx
> +    <Transition.Root show={isOpen} as={Fragment}>
Can we revert back to using the `Modal` component? It contains all the `Dialog` and `Transition.Child` components laid out below.

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/CreatePaymentModal/CreatePaymentModalController.tsx
> +export function CreatePaymentModalController({
Not sure why `onConfirm`  needs to be pulled out into this layer? Seems like it could remain in the `CreatePaymentModal` component?

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/input/Input.tsx
> +  className?: string;
Following through on the conversation from Slack. Can we avoid introducing the `className` as a string pattern?

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/input/InputField.tsx
> +  className = "",
ditto here

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/input/InputGroup.tsx
> +  className = "",
ditto

2021-11-18 23:56 UTC, nickgarfield commented on app/tsconfig.paths.json
> +				"./src/components/*"
@rasreee We chatted earlier about this a few times? We agreed to not introduce the `"./src/components/*"` pattern because the import paths end up getting unnecessarily complicated.

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/input/Select.tsx
> +export function Select({ onChange, selectedOption, formatSelectedOption, options }: SelectProps) {
`Select` component looks good!

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/CreatePaymentModal/CreatePaymentModal.tsx
> +  onConfirm: (data: CreatePaymentFormData) => void;
Types 🙌

2021-11-18 23:56 UTC, nickgarfield commented on app/src/components/CreatePaymentModal/ConfirmationStep.tsx
> +  if (!formData) return null;
Not sure I understand why any changes to this component are needed?

2021-11-19 16:11 UTC, rasreee commented on app/tsconfig.paths.json
> +				"./src/components/*"
some components only import 1 or 2 things from that module, and importing using "@components/*" is more optimal for bundle size than importing using "@components" in those cases.

2021-11-19 16:12 UTC, rasreee commented on app/tsconfig.paths.json
> +				"./src/components/*"
up to you! more than happy to revert this change

2021-11-19 16:12 UTC, rasreee commented on app/src/components/input/Input.tsx
> +  className?: string;
okay! i'll replace this pattern using a custom style prop then

2021-11-19 16:17 UTC, rasreee commented on app/src/components/CreatePaymentModal/CreatePaymentModalController.tsx
> +export function CreatePaymentModalController({
i was trying to separate the modal component into business vs UI logic so i could easily test the UI only - otherwise testing it was really annoying, i would have to keep logging into Phantom and then clicking the modal open just to test the recurrence toggle. instead this allowed me to test by rendering UI component of the modal only without needing to have my wallet connected / test-validator running (referring to the `useFaktor` hook being used in CreatePaymentModalController here)

i can revert this too, it's no problem. just let me know.

2021-11-20 13:15 UTC, nickgarfield approved these changes

2021-11-20 13:15 UTC, merged